//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/yangeric/mIOS/360-j2objc/build/mainTranslationExtraction/com/agrimap/mobile/shared/api/ModelId.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ModelId")
#ifdef RESTRICT_ModelId
#define INCLUDE_ALL_ModelId 0
#else
#define INCLUDE_ALL_ModelId 1
#endif
#undef RESTRICT_ModelId

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if !defined (ComAgrimapMobileSharedApiModelId_) && (INCLUDE_ALL_ModelId || defined(INCLUDE_ComAgrimapMobileSharedApiModelId))
#define ComAgrimapMobileSharedApiModelId_

@class ComGoogleCommonBaseOptional;
@class JavaLangLong;
@protocol JavaUtilCollection;

@interface ComAgrimapMobileSharedApiModelId : NSObject

#pragma mark Public

- (instancetype)init;

- (jboolean)isEqual:(id)o;

- (JavaLangLong *)getId;

+ (ComGoogleCommonBaseOptional *)getIdValueWithComAgrimapMobileSharedApiModelId:(ComAgrimapMobileSharedApiModelId *)id_;

+ (ComGoogleCommonBaseOptional *)getIdValueWithComGoogleCommonBaseOptional:(ComGoogleCommonBaseOptional *)id_;

+ (ComGoogleCommonBaseOptional *)getIdValuesWithJavaUtilCollection:(id<JavaUtilCollection>)ids;

- (void)setIdWithJavaLangLong:(JavaLangLong *)id_;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAgrimapMobileSharedApiModelId)

FOUNDATION_EXPORT ComGoogleCommonBaseOptional *ComAgrimapMobileSharedApiModelId_getIdValueWithComGoogleCommonBaseOptional_(ComGoogleCommonBaseOptional *id_);

FOUNDATION_EXPORT ComGoogleCommonBaseOptional *ComAgrimapMobileSharedApiModelId_getIdValueWithComAgrimapMobileSharedApiModelId_(ComAgrimapMobileSharedApiModelId *id_);

FOUNDATION_EXPORT ComGoogleCommonBaseOptional *ComAgrimapMobileSharedApiModelId_getIdValuesWithJavaUtilCollection_(id<JavaUtilCollection> ids);

FOUNDATION_EXPORT void ComAgrimapMobileSharedApiModelId_init(ComAgrimapMobileSharedApiModelId *self);

J2OBJC_TYPE_LITERAL_HEADER(ComAgrimapMobileSharedApiModelId)

#endif


#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ModelId")
