//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/yangeric/mIOS/360-j2objc/build/mainTranslationExtraction/com/agrimap/mobile/shared/api/ModelId.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "ModelId.h"
#include "com/google/common/base/Optional.h"
#include "java/lang/Long.h"
#include "java/util/ArrayList.h"
#include "java/util/Collection.h"
#include "java/util/List.h"

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

@implementation ComAgrimapMobileSharedApiModelId

- (void)setIdWithJavaLangLong:(JavaLangLong *)id_ {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (JavaLangLong *)getId {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (jboolean)isEqual:(id)o {
  if (self == o) {
    return true;
  }
  if (o == nil || [self getClass] != (id) [o getClass]) {
    return false;
  }
  JavaLangLong *id_ = [self getId];
  ComAgrimapMobileSharedApiModelId *other = (ComAgrimapMobileSharedApiModelId *) cast_chk(o, [ComAgrimapMobileSharedApiModelId class]);
  JavaLangLong *otherId = [other getId];
  return id_ != nil ? [id_ isEqual:otherId] : otherId == nil;
}

- (NSString *)description {
  JavaLangLong *id_ = [self getId];
  return id_ == nil ? nil : [id_ description];
}

+ (ComGoogleCommonBaseOptional *)getIdValueWithComGoogleCommonBaseOptional:(ComGoogleCommonBaseOptional *)id_ {
  return ComAgrimapMobileSharedApiModelId_getIdValueWithComGoogleCommonBaseOptional_(id_);
}

+ (ComGoogleCommonBaseOptional *)getIdValueWithComAgrimapMobileSharedApiModelId:(ComAgrimapMobileSharedApiModelId *)id_ {
  return ComAgrimapMobileSharedApiModelId_getIdValueWithComAgrimapMobileSharedApiModelId_(id_);
}

+ (ComGoogleCommonBaseOptional *)getIdValuesWithJavaUtilCollection:(id<JavaUtilCollection>)ids {
  return ComAgrimapMobileSharedApiModelId_getIdValuesWithJavaUtilCollection_(ids);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComAgrimapMobileSharedApiModelId_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setIdWithJavaLangLong:", "setId", "V", 0x401, NULL, NULL },
    { "getId", NULL, "Ljava.lang.Long;", 0x401, NULL, NULL },
    { "isEqual:", "equals", "Z", 0x1, NULL, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getIdValueWithComGoogleCommonBaseOptional:", "getIdValue", "Lcom.google.common.base.Optional;", 0x9, NULL, "(Lcom/google/common/base/Optional<+Lcom/agrimap/mobile/shared/api/ModelId;>;)Lcom/google/common/base/Optional<Ljava/lang/Long;>;" },
    { "getIdValueWithComAgrimapMobileSharedApiModelId:", "getIdValue", "Lcom.google.common.base.Optional;", 0x9, NULL, "(Lcom/agrimap/mobile/shared/api/ModelId;)Lcom/google/common/base/Optional<Ljava/lang/Long;>;" },
    { "getIdValuesWithJavaUtilCollection:", "getIdValues", "Lcom.google.common.base.Optional;", 0x9, NULL, "(Ljava/util/Collection<+Lcom/agrimap/mobile/shared/api/ModelId;>;)Lcom/google/common/base/Optional<Ljava/util/List<Ljava/lang/Long;>;>;" },
    { "init", "ModelId", NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComAgrimapMobileSharedApiModelId = { 2, "ModelId", "com.agrimap.mobile.shared.api", NULL, 0x401, 8, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComAgrimapMobileSharedApiModelId;
}

@end

ComGoogleCommonBaseOptional *ComAgrimapMobileSharedApiModelId_getIdValueWithComGoogleCommonBaseOptional_(ComGoogleCommonBaseOptional *id_) {
  ComAgrimapMobileSharedApiModelId_initialize();
  if ([((ComGoogleCommonBaseOptional *) nil_chk(id_)) isPresent]) {
    ComAgrimapMobileSharedApiModelId *modelId = [id_ get];
    return ComGoogleCommonBaseOptional_ofWithId_([((ComAgrimapMobileSharedApiModelId *) nil_chk(modelId)) getId]);
  }
  return ComGoogleCommonBaseOptional_absent();
}

ComGoogleCommonBaseOptional *ComAgrimapMobileSharedApiModelId_getIdValueWithComAgrimapMobileSharedApiModelId_(ComAgrimapMobileSharedApiModelId *id_) {
  ComAgrimapMobileSharedApiModelId_initialize();
  if (id_ != nil) {
    if ([id_ getId] != nil) {
      return ComGoogleCommonBaseOptional_ofWithId_([id_ getId]);
    }
  }
  return ComGoogleCommonBaseOptional_absent();
}

ComGoogleCommonBaseOptional *ComAgrimapMobileSharedApiModelId_getIdValuesWithJavaUtilCollection_(id<JavaUtilCollection> ids) {
  ComAgrimapMobileSharedApiModelId_initialize();
  if (ids != nil && ![ids isEmpty]) {
    id<JavaUtilList> list = create_JavaUtilArrayList_init();
    for (ComAgrimapMobileSharedApiModelId * __strong modelId in ids) {
      ComGoogleCommonBaseOptional *id_ = ComAgrimapMobileSharedApiModelId_getIdValueWithComAgrimapMobileSharedApiModelId_(modelId);
      if ([((ComGoogleCommonBaseOptional *) nil_chk(id_)) isPresent]) {
        [list addWithId:[id_ get]];
      }
    }
    if (![list isEmpty]) {
      return ComGoogleCommonBaseOptional_ofWithId_(list);
    }
  }
  return ComGoogleCommonBaseOptional_absent();
}

void ComAgrimapMobileSharedApiModelId_init(ComAgrimapMobileSharedApiModelId *self) {
  NSObject_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComAgrimapMobileSharedApiModelId)

#pragma clang diagnostic pop
